[theme]
primaryColor="#ffffff"  # Example primary color
backgroundColor="#000000"  # Example background color
secondaryBackgroundColor="#f9f7f3"  # Example secondary background color
textColor="#3f4e63"  # Example text color
